version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    cooldown:
      default-days: 3
      semver-major-days: 7
      semver-minor-days: 3
      semver-patch-days: 3
    commit-message:
      prefix: "fix(deps)"
      prefix-development: "chore(deps):"
    assignees:
      - "matteovivona"
    reviewers:
      - "matteovivona"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3
      semver-major-days: 7
      semver-minor-days: 3
      semver-patch-days: 3
    commit-message:
      prefix: "chore(actions)"
    assignees:
      - "matteovivona"
    reviewers:
      - "matteovivona"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3
      semver-major-days: 7
      semver-minor-days: 3
      semver-patch-days: 3
    commit-message:
      prefix: "fix(docker)"
    assignees:
      - "matteovivona"
    reviewers:
      - "matteovivona"
