name: Test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

env:
  PNPM_VERSION: 10.33.0

jobs:
  test:
    runs-on: ubuntu-latest
    name: Coverage
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        name: Checkout
      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc
          package-manager-cache: false
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        name: Install pnpm
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Install with pnpm
        run: pnpm install
      - name: Run tests with coverage
        run: pnpm test:coverage
      - name: Coveralls
        uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329 # master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-error: false # https://status.coveralls.io/incidents/pdbt7vdzlvpj
      - name: CodeClimate
        continue-on-error: true
        uses: paambaati/codeclimate-action@f429536ee076d758a24705203199548125a28ca7 # v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TEST_REPORTER_ID }}
        with:
          coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov
