name: Test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

env:
  PNPM_VERSION: 10.33.0

jobs:
  test:
    runs-on: ubuntu-latest
    name: Coverage
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        name: Checkout
      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .nvmrc
          package-manager-cache: false
      - uses: pnpm/action-setup@078e9d416474b29c0c387560859308974f7e9c53 # v6.0.1
        name: Install pnpm
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Install with pnpm
        run: pnpm install
      - name: Run tests with coverage
        run: pnpm test:coverage
      - name: Coveralls
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-error: false # https://status.coveralls.io/incidents/pdbt7vdzlvpj
      - name: CodeClimate
        continue-on-error: true
        uses: paambaati/codeclimate-action@f429536ee076d758a24705203199548125a28ca7 # v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TEST_REPORTER_ID }}
        with:
          coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov
